### YamlMime:ManagedReference
items:
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  id: ForeignKeyReferenceAlreadyHasValueException
  children:
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  - System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException
  nameWithType: ForeignKeyReferenceAlreadyHasValueException
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  type: Class
  summary: "Представляет ошибки, возникающие при попытке изменить внешний ключ, если сущность уже загружена."
  syntax:
    content: 'public class ForeignKeyReferenceAlreadyHasValueException : InvalidOperationException'
  inheritance:
  - System.InvalidOperationException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  id: '#ctor'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException()
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref> класс системным сообщением, содержащим описание ошибки."
  remarks: "Этот конструктор инициализирует <xref:System.Exception.Message%2A>свойств нового экземпляра системным сообщением, содержащим описание ошибки, например «DefaultMessageDisplayedByParameterlessCtorWriterMustSupply».</xref:System.Exception.Message%2A> Это сообщение учитывает текущую культуру системы.       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.InsufficientMemoryException>.</xref:System.InsufficientMemoryException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Строка локализованного сообщения об. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException ();
    parameters: []
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException(String)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref> класса с указанным сообщением, содержащим описание ошибки."
  remarks: "В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>.</xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке, указываемой `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, описывающее исключение. Код, вызывающий этот конструктор, должен убедиться, что эта строка локализована для текущего языка и региональных параметров системы."
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  langs:
  - csharp
  name: ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  type: Constructor
  assemblies:
  - System.Data.Linq
  namespace: System.Data.Linq
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException&quot;> </xref> класса с указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение."
  remarks: "Исключение, созданное как прямой результат предыдущего исключения, должно содержать ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Свойство возвращает то же значение, которое передается конструктору, или `null` Если <xref:System.Exception.InnerException%2A>свойства не предоставляет конструктору значение внутреннего исключения.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>.</xref:System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| `null`.|   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке, указываемой `message`. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ForeignKeyReferenceAlreadyHasValueException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, описывающее исключение. Код, вызывающий этот конструктор, должен убедиться, что эта строка локализована для текущего языка и региональных параметров системы."
    - id: innerException
      type: System.Exception
      description: "Исключение, которое стало причиной текущего исключения. Если `innerException` не <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, текущее исключение сгенерировано в <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> блок, обрабатывающем внутреннее исключение."
  overload: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.InvalidOperationException
  isExternal: false
  name: System.InvalidOperationException
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException()
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException()
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String)
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException(String)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor(System.String,System.Exception)
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
  fullName: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException.#ctor*
  parent: System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException
  isExternal: false
  name: ForeignKeyReferenceAlreadyHasValueException
  nameWithType: ForeignKeyReferenceAlreadyHasValueException.ForeignKeyReferenceAlreadyHasValueException
