### YamlMime:ManagedReference
items:
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  id: WorkflowTerminatedEventArgs
  children:
  - System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  langs:
  - csharp
  name: WorkflowTerminatedEventArgs
  nameWithType: WorkflowTerminatedEventArgs
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  type: Class
  summary: "Предоставляет данные для <xref href=&quot;System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated&quot;> </xref> событий."
  remarks: "> [!NOTE] >  [!INCLUDE[DeprecatedContent](~/add/includes/ajax-current-ext-md.md)]Экземпляр рабочего процесса может быть завершен одним из трех способов: узел может вызвать метод <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>, <xref:System.Workflow.ComponentModel.TerminateActivity>действия могут вызываться из экземпляра рабочего процесса или механизм среды выполнения рабочего процесса экземпляра может быть прервано из-за необработанного исключения.</xref:System.Workflow.ComponentModel.TerminateActivity> </xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> При завершении экземпляра рабочего процесса механизм среды выполнения рабочего процесса вызывает <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>событий.</xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName> Узел может подписаться на это событие, добавив обработчик событий <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>.</xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>"
  example:
  - "The following code example demonstrates an event handler method that takes WorkflowTerminatedEventArgs as a parameter. The `OnWorkflowTerminated` method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception%2A> property get the message associated with the exception that caused the workflow to terminate.  \n  \n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \n  \n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]"
  syntax:
    content: >-
      [System.Obsolete("The System.Workflow.* types are deprecated.  Instead, please use the new types from System.Activities.*")]

      public class WorkflowTerminatedEventArgs : System.Workflow.Runtime.WorkflowEventArgs
  inheritance:
  - System.EventArgs
  - System.Workflow.Runtime.WorkflowEventArgs
  implements: []
  inheritedMembers:
  - System.Workflow.Runtime.WorkflowEventArgs.WorkflowInstance
  platform:
  - net462
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  id: Exception
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  langs:
  - csharp
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  type: Property
  assemblies:
  - System.Workflow.Runtime
  namespace: System.Workflow.Runtime
  summary: "Возвращает исключение, которое вызвало завершение экземпляра рабочего процесса."
  remarks: "Когда экземпляр рабочего процесса завершается из-за необработанного исключения, исключение содержит необработанное исключение.       Если экземпляр рабочего процесса завершается вызовом либо узла <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>или <xref:System.Workflow.ComponentModel.TerminateActivity>исключение содержит действия, <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>с его <xref:System.Exception.Message%2A>Свойства, значение которого является описание причины завершения.</xref:System.Exception.Message%2A> </xref:System.Workflow.ComponentModel.WorkflowTerminatedException> </xref:System.Workflow.ComponentModel.TerminateActivity> </xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> Если выполнение экземпляра рабочего процесса завершает узел, то он передает это описание в `string` параметра <xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName>.</xref:System.Workflow.Runtime.WorkflowInstance.Terminate%2A?displayProperty=fullName> Если экземпляр рабочего процесса завершается <xref:System.Workflow.ComponentModel.TerminateActivity>Описание поставляется свойством <xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName>.</xref:System.Workflow.ComponentModel.TerminateActivity.Error%2A?displayProperty=fullName> </xref:System.Workflow.ComponentModel.TerminateActivity>      Настроек [!NOTE] настроек несмотря на то что в случае, когда <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>событие, которое не из-за необработанного исключения, механизм среды выполнения рабочих процессов включает описание причины завершения в <xref:System.Exception.Message%2A>свойство <xref:System.Workflow.ComponentModel.WorkflowTerminatedException>, он не обязательно вызывает это исключение.</xref:System.Workflow.ComponentModel.WorkflowTerminatedException> </xref:System.Exception.Message%2A> </xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated?displayProperty=fullName>"
  example:
  - "The following code example demonstrates how you can use the Exception property to obtain information about an exception that caused a workflow to terminate. The `OnWorkflowTerminated` method takes a <xref:System.Workflow.Runtime.WorkflowTerminatedEventArgs> as a parameter. This method is called when the <xref:System.Workflow.Runtime.WorkflowRuntime.WorkflowTerminated> event is raised. The code uses the Exception property get the message associated with the exception that caused the workflow to terminate.  \n  \n This code example is part of the Sequential Workflow with Parameters SDK Sample from the Program.cs file. For more information, see [Sequential Workflow with Parameters](http://msdn.microsoft.com/en-us/17157f2d-8fed-4848-a386-e4efa381b66b).  \n  \n [!code-cs[WF_Samples#193](~/add/codesnippet/csharp/wf_snippets/snippets19.cs#193)]\n [!code-vb[WF_Samples#193](~/add/codesnippet/visualbasic/wf_snippets/snippets19.vb#193)]"
  syntax:
    content: public Exception Exception { get; }
    return:
      type: System.Exception
      description: "<xref:System.Exception>, Который вызвал экземпляр рабочего процесса, подлежащего прерыванию.</xref:System.Exception>"
  overload: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Workflow.Runtime.WorkflowEventArgs
  isExternal: false
  name: System.Workflow.Runtime.WorkflowEventArgs
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  isExternal: false
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
  fullName: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Workflow.Runtime.WorkflowTerminatedEventArgs.Exception*
  parent: System.Workflow.Runtime.WorkflowTerminatedEventArgs
  isExternal: false
  name: Exception
  nameWithType: WorkflowTerminatedEventArgs.Exception
