### YamlMime:ManagedReference
items:
- uid: System.Workflow.Activities.Rules.RuleEvaluationException
  id: RuleEvaluationException
  children:
  - System.Workflow.Activities.Rules.RuleEvaluationException.#ctor
  - System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String)
  - System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: RuleEvaluationException
  nameWithType: RuleEvaluationException
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException
  type: Class
  summary: "Представляет базовый класс для всех исключений, вызываемых проблемами вычисления правил."
  syntax:
    content: 'public class RuleEvaluationException : System.Workflow.Activities.Rules.RuleException'
  inheritance:
  - System.Exception
  - System.Workflow.Activities.Rules.RuleException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor
  id: '#ctor'
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  langs:
  - csharp
  name: RuleEvaluationException()
  nameWithType: RuleEvaluationException.RuleEvaluationException()
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException()
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Workflow.Activities.Rules.RuleEvaluationException&quot;> </xref> класса."
  remarks: "Этот конструктор инициализирует <xref:System.Exception.Message%2A>свойств нового экземпляра системным сообщением, которое описывает ошибку и учитывает текущую культуру системы.</xref:System.Exception.Message%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Workflow.Activities.Rules.RuleEvaluationException>.</xref:System.Workflow.Activities.Rules.RuleEvaluationException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic). |   | <xref:System.Exception.Message%2A>| Локализованное описание, объект системного. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public RuleEvaluationException ();
    parameters: []
  overload: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  langs:
  - csharp
  name: RuleEvaluationException(String)
  nameWithType: RuleEvaluationException.RuleEvaluationException(String)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(String)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Workflow.Activities.Rules.RuleEvaluationException&quot;> </xref> класса с указанным сообщением об ошибке."
  remarks: "Этот конструктор инициализирует <xref:System.Exception.Message%2A>нового экземпляра, используя свойство `message` параметр.</xref:System.Exception.Message%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Workflow.Activities.Rules.RuleEvaluationException>.</xref:System.Workflow.Activities.Rules.RuleEvaluationException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic). |   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public RuleEvaluationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, описывающее ошибку."
  overload: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  langs:
  - csharp
  name: RuleEvaluationException(SerializationInfo,StreamingContext)
  nameWithType: RuleEvaluationException.RuleEvaluationException(SerializationInfo,StreamingContext)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Workflow.Activities.Rules.RuleEvaluationException&quot;> </xref> сериализованными данными."
  remarks: "Данный конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке."
  syntax:
    content: protected RuleEvaluationException (System.Runtime.Serialization.SerializationInfo serializeInfo, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: serializeInfo
      type: System.Runtime.Serialization.SerializationInfo
      description: "<xref href=&quot;System.Runtime.Serialization.SerializationInfo&quot;> </xref> , Содержащий сериализованные данные объекта о вызываемом исключении."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "<xref:System.Runtime.Serialization.StreamingContext>, Содержащий контекстные сведения об источнике или назначении.</xref:System.Runtime.Serialization.StreamingContext>"
  overload: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  langs:
  - csharp
  name: RuleEvaluationException(String,Exception)
  nameWithType: RuleEvaluationException.RuleEvaluationException(String,Exception)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(String,Exception)
  type: Constructor
  assemblies:
  - System.Workflow.Activities
  namespace: System.Workflow.Activities.Rules
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.Workflow.Activities.Rules.RuleEvaluationException&quot;> </xref> класса с указанным сообщением об ошибке и ссылкой на внутреннее <xref:System.Exception>, являющееся причиной <xref:System.Exception>.</xref:System.Exception> </xref:System.Exception>"
  remarks: "<xref:System.Exception>, Созданное как прямой результат предыдущего <xref:System.Exception>должно включать ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> </xref:System.Exception> </xref:System.Exception> <xref:System.Exception.InnerException%2A>Свойство возвращает то же значение, которое передается конструктору, или пустую ссылку (`Nothing`) Если <xref:System.Exception.InnerException%2A>свойство не поддерживает внутренний <xref:System.Exception>в конструктор значение.</xref:System.Exception> </xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.Workflow.Activities.Rules.RuleEvaluationException>.</xref:System.Workflow.Activities.Rules.RuleEvaluationException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Внутренняя <xref:System.Exception>ссылка. |   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке. |</xref:System.Exception.Message%2A> </xref:System.Exception> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public RuleEvaluationException (string message, Exception ex);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, описывающее ошибку."
    - id: ex
      type: System.Exception
      description: "<xref:System.Exception>, Являющееся причиной текущего <xref:System.Exception>.</xref:System.Exception> </xref:System.Exception> Если `innerException` параметр не является указателем null (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> в Visual Basic), <xref:System.Exception>возникает в блоке catch, обрабатывающем внутреннее исключение <xref:System.Exception>.</xref:System.Exception> </xref:System.Exception> текущего"
  overload: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Workflow.Activities.Rules.RuleException
  isExternal: false
  name: System.Workflow.Activities.Rules.RuleException
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException()
  nameWithType: RuleEvaluationException.RuleEvaluationException()
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException()
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String)
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException(String)
  nameWithType: RuleEvaluationException.RuleEvaluationException(String)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException(SerializationInfo,StreamingContext)
  nameWithType: RuleEvaluationException.RuleEvaluationException(SerializationInfo,StreamingContext)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor(System.String,System.Exception)
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException(String,Exception)
  nameWithType: RuleEvaluationException.RuleEvaluationException(String,Exception)
  fullName: System.Workflow.Activities.Rules.RuleEvaluationException.RuleEvaluationException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.Workflow.Activities.Rules.RuleEvaluationException.#ctor*
  parent: System.Workflow.Activities.Rules.RuleEvaluationException
  isExternal: false
  name: RuleEvaluationException
  nameWithType: RuleEvaluationException.RuleEvaluationException
