### YamlMime:ManagedReference
items:
- uid: System.ApplicationException
  id: ApplicationException
  children:
  - System.ApplicationException.#ctor
  - System.ApplicationException.#ctor(System.String)
  - System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.ApplicationException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ApplicationException
  nameWithType: ApplicationException
  fullName: System.ApplicationException
  type: Class
  summary: "Служит базовым классом для определяемых приложением исключений."
  remarks: >-
    > [!IMPORTANT]

    >  You should derive custom exceptions from the <xref:System.Exception> class rather than the ApplicationException class.  You should not throw an ApplicationException exception in your code, and you should not catch an ApplicationException exception unless you intend to re-throw the original exception.
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class ApplicationException : Exception
  inheritance:
  - System.Exception
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor
  id: '#ctor'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException()
  nameWithType: ApplicationException.ApplicationException()
  fullName: System.ApplicationException.ApplicationException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.ApplicationException&quot;> </xref> класса."
  remarks: "Этот конструктор инициализирует <xref:System.Exception.Message%2A>свойство нового экземпляра системным сообщением, которое описывает ошибку, например «произошла ошибка приложения».</xref:System.Exception.Message%2A> Это сообщение учитывает текущую культуру системы.       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.ApplicationException>.</xref:System.ApplicationException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic). |   | <xref:System.Exception.Message%2A>| Строка локализованного сообщения об. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ApplicationException ();
    parameters: []
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException(String)
  nameWithType: ApplicationException.ApplicationException(String)
  fullName: System.ApplicationException.ApplicationException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.ApplicationException&quot;> </xref> класса с указанным сообщением об ошибке."
  remarks: "Содержимое `message` параметр должен быть понятным пользователю. Код, вызывающий этот конструктор, должен убедиться, что эта строка локализована для текущего языка и региональных параметров системы.       Это сообщение учитывает текущую культуру системы.       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.ApplicationException>.</xref:System.ApplicationException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Пустая ссылка (`Nothing` в Visual Basic). |   | `Message`| Строка сообщения об ошибке. |</xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ApplicationException (string message);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение, описывающее ошибку."
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException(SerializationInfo,StreamingContext)
  nameWithType: ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
  fullName: System.ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.ApplicationException&quot;> </xref> сериализованными данными."
  remarks: "Данный конструктор вызывается в процессе десериализации для воссоздания объекта исключения, переданного в потоке. Дополнительные сведения см. в разделе [сериализации XML и SOAP](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: protected ApplicationException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "Объект, содержащий сериализованные данные объекта."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "Контекстные сведения об источнике или назначении."
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ApplicationException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.ApplicationException
  langs:
  - csharp
  name: ApplicationException(String,Exception)
  nameWithType: ApplicationException.ApplicationException(String,Exception)
  fullName: System.ApplicationException.ApplicationException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Инициализирует новый экземпляр <xref href=&quot;System.ApplicationException&quot;> </xref> класса с указанным сообщением об ошибке и ссылкой на внутреннее исключение, вызвавшее данное исключение."
  remarks: "Содержимое `message` параметр должен быть понятным пользователю. Код, вызывающий этот конструктор, должен убедиться, что эта строка локализована для текущего языка и региональных параметров системы.       Исключение, созданное как прямой результат предыдущего исключения, должно содержать ссылку на предыдущее исключение в <xref:System.Exception.InnerException%2A>свойство.</xref:System.Exception.InnerException%2A> <xref:System.Exception.InnerException%2A>Свойство возвращает то же значение, которое было передано конструктору, или пустая ссылка, если <xref:System.Exception.InnerException%2A>свойства не предоставляет конструктору значение внутреннего исключения.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       В следующей таблице показаны исходные значения свойств для экземпляра класса <xref:System.ApplicationException>.</xref:System.ApplicationException>      | Свойство | Значение |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Ссылка на внутреннее исключение. |   | <xref:System.Exception.Message%2A>| Строка сообщения об ошибке. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ApplicationException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "Сообщение об ошибке с объяснением причин исключения."
    - id: innerException
      type: System.Exception
      description: "Исключение, которое стало причиной текущего исключения. Если `innerException` параметр не является указателем null, текущее исключение сгенерировано в <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> блок, обрабатывающем внутреннее исключение."
  overload: System.ApplicationException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.Exception
  isExternal: false
  name: System.Exception
- uid: System.ApplicationException.#ctor
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException()
  nameWithType: ApplicationException.ApplicationException()
  fullName: System.ApplicationException.ApplicationException()
- uid: System.ApplicationException.#ctor(System.String)
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException(String)
  nameWithType: ApplicationException.ApplicationException(String)
  fullName: System.ApplicationException.ApplicationException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ApplicationException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException(SerializationInfo,StreamingContext)
  nameWithType: ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
  fullName: System.ApplicationException.ApplicationException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.ApplicationException.#ctor(System.String,System.Exception)
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException(String,Exception)
  nameWithType: ApplicationException.ApplicationException(String,Exception)
  fullName: System.ApplicationException.ApplicationException(String,Exception)
- uid: System.ApplicationException.#ctor*
  parent: System.ApplicationException
  isExternal: false
  name: ApplicationException
  nameWithType: ApplicationException.ApplicationException
